chromium->monyhar
monyhar/monyhar pull request #17
Opened 2021-06-13 16:51 UTC by zhullyb

2021-06-14 00:13 UTC, RtYkk approved these changes
LOL

2021-06-14 04:30 UTC, ouuan commented
> RtYkk approved these changes

你是怎么打开 https://github.com/monyhar/monyhar/pull/17/files 的 :thinking:

![图片](https://user-images.githubusercontent.com/30581822/121839315-4b350680-cd0c-11eb-8a48-752c80cc87f6.png)

2021-06-14 04:49 UTC, livrth approved these changes

2021-06-14 04:52 UTC, zhullyb commented
> > RtYkk approved these changes
> 
> 你是怎么打开 https://github.com/monyhar/monyhar/pull/17/files 的 thinking
> 
> ![图片](https://user-images.githubusercontent.com/30581822/121839315-4b350680-cd0c-11eb-8a48-752c80cc87f6.png)

这里能看到一部分更改，其他的也没办法了，只能本地查看了
https://github.com/zhullyb/monyhar/commit/7cfbb75a42dad3309c98150cb67c69a8f8bc0981

2021-06-14 05:10 UTC, ouuan commented
可以不打开 Files changed 而 approve 吗

2021-06-14 05:10 UTC, ouuan commented
貌似可以用 github cli

2021-06-14 05:21 UTC, ouuan requested changes
1.  需要按许可证要求保留版权信息。
2.  邮件地址等不应修改。

2021-06-14 05:30 UTC, zhullyb commented
似乎确实是个问题
________________________________
From: Yufan You ***@***.***>
Sent: Monday, June 14, 2021 1:21:46 PM
To: monyhar/monyhar ***@***.***>
Cc: zhullyb ***@***.***>; Author ***@***.***>
Subject: Re: [monyhar/monyhar] chromium->monyhar (#17)


@ouuan requested changes on this pull request.

  1.  需要按许可证要求保留版权信息。
  2.  邮件地址等不应修改。

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/monyhar/monyhar/pull/17#pullrequestreview-682522815>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKKMTFTHO45LHYS3EFH65CLTSWGWVANCNFSM46T46LTA>.

2021-06-14 05:59 UTC, VincentXWD commented
LGTM

2021-06-14 12:01 UTC, yang-han approved these changes

2021-06-14 12:53 UTC, gnaggnoyil commented
LGTM, plz merge ASAP.

2021-06-14 15:32 UTC, WuzgXY-GitHub commented
> 可以不打开 Files changed 而 approve 吗

移动版可以，就像这样 ⬇️

2021-06-14 15:32 UTC, WuzgXY-GitHub approved these changes

2021-06-14 19:24 UTC, njzjz requested changes
Here is still Chromium:
https://github.com/monyhar/monyhar/blob/7cfbb75a42dad3309c98150cb67c69a8f8bc0981/monyhar/docs/README.md#L1

2021-06-14 19:52 UTC, njzjz requested changes

2021-06-14 19:52 UTC, njzjz commented on monyhar/PRESUBMIT.py
>      "correct_name": "Chromium",
```suggestion
     "correct_name": "Monyhar",
```
I think you didn't replace capitalized words?

2021-06-14 19:52 UTC, njzjz commented on monyhar/android_webview/docs/quick-start.md
> +Try building Chromium. If that doesn't work, please reach out to [the monyhar
```suggestion
Try building Monyhar. If that doesn't work, please reach out to [the monyhar
```

2021-06-15 03:53 UTC, chemicalfiber commented on monyhar/android_webview/docs/quick-start.md
> +Try building Chromium. If that doesn't work, please reach out to [the monyhar
此网页专为旧版梦弘浏览器打造😂

2021-06-15 05:30 UTC, lzjluzijie commented
我怀疑此PR涉嫌抄袭鸿蒙OS

2021-06-15 05:32 UTC, lzjluzijie approved these changes

2021-06-15 05:34 UTC, Zxilly approved these changes

2021-06-15 13:02 UTC, canyie approved these changes

2021-06-15 14:10 UTC, tangkg commented
同志们我来晚啦

2021-06-15 14:17 UTC, linonetwo commented
![截屏2021-06-15 下午10 16 52](https://user-images.githubusercontent.com/3746270/122068971-66486900-ce27-11eb-9c9e-22c84c08642b.png)
第一次见到这么大量的改动，中国人太勤奋了！

2021-06-16 07:31 UTC, BryantSuen approved these changes

2021-06-16 16:32 UTC, dingwen07 approved these changes

2021-06-17 07:28 UTC, lwqwag commented on monyhar/PRESUBMIT.py
>      "correct_name": "Chromium",
此处是灵魂

2021-06-17 08:18 UTC, ousc approved these changes
LGTM

2021-06-17 11:46 UTC, gnaggnoyil approved these changes

2021-06-17 16:10 UTC, SekiBetu approved these changes

2021-06-18 05:37 UTC, kongminhao approved these changes

2021-06-18 13:22 UTC, code004Accepted requested changes
不把`com.google.android.apps.chrome`也改一下嘛（

2021-06-20 15:47 UTC, Cotch22 approved these changes
太感人了！monyhar工程师日日夜夜，终于实现了兼容chromium，泪目！

2021-06-21 14:58 UTC, Magic-Xin approved these changes

2021-06-22 06:30 UTC, ruan4261 reviewed
建议将邮箱统一改为大陆域名

2021-08-09 10:41 UTC, gclmichael commented
警惕境外势力打开源牌，共同维护我国重大开源项目Monyhar！

2025-12-08 08:34 UTC, closed without merging